### ISSUE TITLE
Atomic file read/writes 

### ISSUE THREAD

**Issue by saurabh0719** [saurabh0719/elara#19]
#### Description :  

* Ideally, files writes and reads should be fully [atomic](https://en.wikipedia.org/wiki/Atomicity_(database_systems)) to avoid file corruption 
* The [Safer](https://github.com/rec/safer) library is handy for this usecase. 
  - This library essentially directs all file writes to a memory stream (or temp file) before writing into the actual file to ensure atomicity.

Comment any other suggestions or alternatives.

**Comment by AdityaKotwal100** [comment]
Interested in doing this.

**Comment by saurabh0719** [comment]
Great. Check out the [contributing guidelines](https://github.com/saurabh0719/elara/blob/main/CONTRIBUTING.md) before you proceed @AdityaKotwal100
