### ISSUE TITLE
Your encrypted storage can benefit from a binary encoding scheme

### ISSUE THREAD

**Issue by DarthUdp** [saurabh0719/elara#6]
I would like to suggest at elara.elarautil.Util.encryptAndStore you use a binary encoding scheme like msgpack or to dump as json and encode as utf-8 and that will give you bytes to encrypt and then store while reliably being able to get the data back, the way it is right now you encode as ASCII (not compatible with utf-8 that might exist in the db) causing possible data loss, and saving the encoding to base64 round trip.

These are quite trivial changes, but I can help you implement them if you need help.
edit: also a hash/checksum to both encrypted and not ways might be a good idea.

**Comment by saurabh0719** [comment]
Hi @DarthUdp 

Great catch there :) 
I'd be happy to assign this issue to you if you want change the encoding to make it utf friendly. 

The checksum however is already on its way, I'll release an update asap.

**Comment by DarthUdp** [comment]
Do assign it then, it should be a quick fix

**Comment by saurabh0719** [comment]
@DarthUdp assigned it to you.

**Comment by DarthUdp** [comment]
@saurabh0719 there are some formatting issues with the code, as a suggestion if you don't mind, there is a tool called black that will fix and make all the code consistently formatted.

**Comment by DarthUdp** [comment]
And the docstrings at the files should be double quotes, sorry for the nitpicks :)

**Comment by saurabh0719** [comment]
> And the docstrings at the files should be double quotes, sorry for the nitpicks :)

No problem, thanks for the tips :)

**Comment by saurabh0719** [comment]
@DarthUdp If you're still interested would you like to take up the checksum() function as well? I think you can do it with `md5.hexdigest()` from the `hashlib` library. I will probably shift my focus more towards formatting and fixing certain other issues that I have planned.

**Comment by DarthUdp** [comment]
@saurabh0719 Just a side note, md5 is considered deprecated and should not be used anymore, also it's a hashing algorithm, a checksum is something like crc32, if doing hashes something like sha-256 should be used if doing checksums crc32 is a popular choice.

**Comment by DarthUdp** [comment]
Just open another issue and assign me I will have a look when I have some spare time tomorrow

**Comment by saurabh0719** [comment]
> @saurabh0719 Just a side note, md5 is considered deprecated and should not be used anymore, also it's a hashing algorithm, a checksum is something like crc32, if doing hashes something like sha-256 should be used if doing checksums crc32 is a popular choice.

Yes good point, I ended up reading a bit about crc

**Comment by saurabh0719** [comment]
> Just open another issue and assign me I will have a look when I have some spare time tomorrow

I've opened a new issue, unable to assign it to you however (idk why), but I've mentioned you.
